---
# Project Information
site_name: AO3 Disco Ranking
site_author: Kevin Alex Zhang
site_description: This repository hosts the ranking models used by the AO3 Discovery Engine.

# Repository information
repo_name: k15z/ao3-disco-ranking
repo_url: https://github.com/k15z/ao3-disco-ranking
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Kevin Alex Zhang

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k15z
      name: k15z on GitHub

# Page tree
nav:
  - Home: index.md
  - Benchmark: benchmark.md
