---
name: Code Quality Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Unit & Coverage test with pytest
        run: poetry run pytest
      
      - name: Check imports with isort
        run: poetry run isort --profile black --check ao3_disco_ranking tests
      - name: Check format with black
        run: poetry run black --check ao3_disco_ranking/ tests/
      - name: Check type hinting with mypy
        run: poetry run mypy --config-file=mypy.ini ao3_disco_ranking/
